import type { mLayanan } from "database/schema";

export const layananS1: typeof mLayanan.$inferInsert[] = [
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "AMS", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "ETRANSPORT & EMEETING", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "PLN KITA", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "ICOFR", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "PLN DAILY", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "PLN FIT", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "WEB KORPORAT", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "MAXICO EPI", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "MOTION TCO", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "MOTION PMO", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "CSMS", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "Cash management CRM BAG", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "Cash Management Odoo", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "ITEMS", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "ESPPD", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "Maxico PLN", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "SMARTER", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "PLN Cerdas", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "PMO PLN", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "SILM PLN", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "Alih Daya", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "DMovement", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "Dashboard CR JR", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "LISDES", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "SPIN", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "IET", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "GASPRO", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "SIDITA", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "RPA EPI", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "ERBAS", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "NEWVC", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "E-PROC BAG", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "CRM FM BAG", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "CRM FM BBN", idSubBidang: "s1" },
    { idLayanan: Bun.randomUUIDv7(), namaLayanan: "BDTC", idSubBidang: "s1" },
];

export const mapLayananS1 = Object.fromEntries(layananS1.map((layanan) => [layanan.namaLayanan, layanan.idLayanan]));